/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("RequestsObjectPageObjectPage journey");

        opaTest("Navigate to RequestsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheRequestsListGenerated.onFilterBar().iExecuteSearch();

            Then.onTheRequestsListGenerated.onTable().iCheckRows();
            When.onTheRequestsListGenerated.onTable().iPressRow(0);

            Then.onTheRequestsObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheRequestsObjectPageGenerated.iCheckNumberOfSections(3);
            When.onTheRequestsObjectPageGenerated.iPressSectionIconTabFilterButton("General");
            Then.onTheRequestsObjectPageGenerated.iCheckSection({ section: "General" });
            Then.onTheRequestsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "title" });
            Then.onTheRequestsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "description" });
            Then.onTheRequestsObjectPageGenerated.onForm({ section: "General" }).iCheckField({ property: "businessPartnerId" });
            When.onTheRequestsObjectPageGenerated.iPressSectionIconTabFilterButton("Processing");
            Then.onTheRequestsObjectPageGenerated.iCheckSection({ section: "Processing" });
            Then.onTheRequestsObjectPageGenerated.onForm({ section: "Processing" }).iCheckField({ property: "status" });
            Then.onTheRequestsObjectPageGenerated.onForm({ section: "Processing" }).iCheckField({ property: "requestType" });
            Then.onTheRequestsObjectPageGenerated.onForm({ section: "Processing" }).iCheckField({ property: "priority" });
            Then.onTheRequestsObjectPageGenerated.onForm({ section: "Processing" }).iCheckField({ property: "assignedProcessorId" });
            When.onTheRequestsObjectPageGenerated.iPressSectionIconTabFilterButton("Audit");
            Then.onTheRequestsObjectPageGenerated.iCheckSection({ section: "Audit" });
            Then.onTheRequestsObjectPageGenerated.onForm({ section: "Audit" }).iCheckField({ property: "createdAt" });
            Then.onTheRequestsObjectPageGenerated.onForm({ section: "Audit" }).iCheckField({ property: "createdBy" });
            Then.onTheRequestsObjectPageGenerated.onForm({ section: "Audit" }).iCheckField({ property: "modifiedAt" });
            Then.onTheRequestsObjectPageGenerated.onForm({ section: "Audit" }).iCheckField({ property: "modifiedBy" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});